### ISSUE TITLE
Spacing between hero button and the graphic

### ISSUE THREAD

**Issue by cogentgene** [stratum-mining/stratumprotocol.org#100]
I noticed we have a huge space between the Hero button and the graphic. Originally, I designed to have the content follow right below the button. I was just curious if there were some internal discussions that perhaps I was not a part of where it was collectively decided to make the hero section full screen heigh? 

If not, what are your thoughts on reducing the gap between the button and the image? Here is what it looks like in the design: 
![CleanShot 0004-09-12 at 00 20 43@2x](https://user-images.githubusercontent.com/3827304/189535523-6a5d3410-b0de-4dcc-89b0-123b9a3ed5a6.jpg)

vs. current:
![CleanShot 0004-09-12 at 00 23 12@2x](https://user-images.githubusercontent.com/3827304/189535582-82587f1e-6289-449c-9d7a-cb3daae2b48a.jpg)

**Comment by cogentgene** [comment]
Not sure if I looked at the latest version (sorry still trying to figure out GH...) but the one I  looked at still had min-h-screen set on it, which would most certainly leave the space in place. 
![CleanShot 0004-09-15 at 00 19 40@2x](https://user-images.githubusercontent.com/3827304/190195988-84c51cd3-de59-4011-a2f3-7dd537da76be.jpg)

**Comment by secondl1ght** [comment]
Ok I'll take another look.

**Comment by secondl1ght** [comment]
The `min-h-screen` shouldn't affect the space you are pointing to in diagram, but there was some extra Y padding on mobile that I removed. I am putting in a PR so you can check the preview link and can let me know if you can still reproduce, I tested on many different screen widths and heights and could not reproduce this gap.
