### ISSUE TITLE
Adjust doc navbar height on desktop scroll

### ISSUE THREAD

**Issue by cogentgene** [stratum-mining/stratumprotocol.org#104]
I like the idea of a fixed header on scroll, but can we adjust it's height to be smaller? Right now it feels like it takes up a lot of room. For reference, we can look at the GitHub's navbar height.

![CleanShot 0004-09-12 at 08 51 30@2x](https://user-images.githubusercontent.com/3827304/189554240-d091454c-8981-4235-8073-523bc645af96.jpg)

![CleanShot 0004-09-12 at 08 48 57@2x](https://user-images.githubusercontent.com/3827304/189554194-66f7b074-29bf-487b-a1af-38763ccd26b5.jpg)

**Comment by pavlenex** [comment]
@secondl1ght I assume this PR was not supposed to address the title going into the header when you click on it in the sidebar or arrive to it from a link?

![Screenshot 2022-09-14 at 18 57 27](https://user-images.githubusercontent.com/36959754/190216762-d4a9a870-f857-424f-885b-510acdaf055a.png)

**Comment by secondl1ght** [comment]
@pavlenex no this was just to address the linked issue, I think @SeraBocca was going to work on this bug fix?
