### ISSUE TITLE
Remove the roadmap section

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#112]
Unfortunatelly, we'll have to make website a bit more protocol-centric than implementation centric. This will require some modifications, but one of the easiest is to (for now) remove the roadmap section from the home page.

In the future we can consider adding it back.

**Comment by secondl1ght** [comment]
Really? It looks so good though! lol

**Comment by cogentgene** [comment]
Bummer :( I feel like without that section the page just looks so short and unimpressive. But, gotta do what you gotta do.

**Comment by pavlenex** [comment]
@cogentgene Agreed, but I'm sure we'll find some different content to fill it up, I don't think it's a wasted effort since in the future we can always add it to our /implementation page or whatever we decide on :)

**Comment by SeraBocca** [comment]
@pavlenex i remove this section in this [PR](https://github.com/stratum-mining/stratumprotocol.org/pull/114) but I agree with all, we defo need to find a new place for that part
