### ISSUE TITLE
Add new section that credits the original protocol creators and tells a bit of a story around how SV2 came to be

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#113]
This section will credit the original creators of SV2 and tell the story in 2-3 paragraphs. Copy is required before we figure out how to design it.

- [ ] @sqcken and @moneyball @pavlenex figure out the copy
- [x] Design
- [x] Implement design

**Comment by pavlenex** [comment]
@SeraBocca @secondl1ght I think we can add this one now, even without the copy with placeholders, and we can later or replace with actual copy, design is on figma now.
![Screenshot 2022-09-29 at 21 48 27](https://user-images.githubusercontent.com/36959754/193128151-215406a4-99b7-421d-9b2c-7fbf09c61ad9.png)

**Comment by moneyball** [comment]
I think something along the lines of "Stratum v2 specification authors" is better than "Meet the inventors of sv2."
