### ISSUE TITLE
Add header menu

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#117]
Add a header menu as per design on Figma.

- Home
- Reference implementation linking to https://github.com/stratum-mining/stratum
- Documentation /overview.html
- Specification linking to /specification.html 

![Screenshot 2022-09-29 at 21 30 46](https://user-images.githubusercontent.com/36959754/193125836-c92a7d8c-2767-458c-a6af-86aa2eff8adf.png)

**Comment by yadavsairaj** [comment]
hey can i take on this task?

**Comment by pavlenex** [comment]
@yadavsairaj Sure, but we're on a very tight time-frame so could you commit to doing it in the next day or two?
Here's a figma file https://www.figma.com/file/JRRRCgwbsfTFo754uoa4hT/Stratum-(Copy)?node-id=0%3A1 where you can check the specifics about design for the header menu.

**Comment by yadavsairaj** [comment]
apologies! @pavlenex

**Comment by yadavsairaj** [comment]
Apologies i wont be able to work on this.

**Comment by acidbunny21** [comment]
@pavlenex should we have this design on both home and documentation layout ? if not i don't really see the need the highlight the current page on the nav since all of the items except the first one redirect to external site or a different page with different nav

**Comment by pavlenex** [comment]
Good point about the highlight. I think we should have consistency so let's have the same header in docs? What do you think @acidbunny21 ?

**Comment by acidbunny21** [comment]
yep i think that's a good idea, but we need to figure out which items we want in the nav bar since the ones on the figma home layout are not the same as the ones on the documentation layout for now

**Comment by acidbunny21** [comment]
also, maybe we can have a discussion with designers to get their POVs

**Comment by pavlenex** [comment]
I think we should have consistent mane, especially now when we have a handful of internal pages, we can always expand later on.

What do you think about moving the documentation titles in the navigation itself? It could look like something we have at https://docs.btcpayserver.org

![Screenshot 2022-10-03 at 09 42 33](https://user-images.githubusercontent.com/36959754/193527878-4f047413-7aeb-4d57-aaf1-e262a9ae9672.png)

Does this make sense to you? I mean we can always do a header for the homepage, and discuss if we want it in docs as well.

cc @cogentgene @Kodylow Thoughts on having a consistent navigaiton accross docs and homepage and also to moving section links to the sidebar.
