### ISSUE TITLE
Configuration box on mobile isn't obvious

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#133]
It's not really clear on mobile that there are multiple choice options. How can we improve this?![image](https://user-images.githubusercontent.com/36959754/194777228-e67ed5db-8042-47f2-85b6-518d554cd949.jpeg)

**Comment by GitGab19** [comment]
@pavlenex I made a simple proposal in my #139, adapting the same structure used for medium/large devices.
I hope you will like it
