### ISSUE TITLE
Tutorial(s)

### ISSUE THREAD

**Issue by Sjors** [stratum-mining/stratumprotocol.org#138]
The landing page has a really pretty "Flexible configurations" diagram. This would be a good place to link to a tutorial.

I think Scenario C would be a good one to start with. Given someone who already has a machine, if they know how to change the pool URL, guide them through the process of using a Stratum V2 pool. Presumably they need to own a domain, a run a linux server with nginx. But then what?

From there you could make a tutorial to setup D, where you have them install their own node on the linux box and propose templates.

Bonus points if the whole setup can be tested on regtest (or a low PoW custom Signet) with a simple CPU miner.

**Comment by pavlenex** [comment]
Heya @Sjors hope all is well, thanks for reporting this and testing things around 😄 You kept your promise from Amsterdam 🎉 

I 100% agree that the configuration C, is a good starting point, at this moment, it's the only config we shipped.

If you would like to try out the config C, you can [check translation proxy tutorial here,](https://github.com/stratum-mining/stratum/tree/main/roles/translator#sv1-to-sv2-translator-proxy) be aware that currently we're still fixing a few bugs in our SRI (Stratum Reference implementation) pool, so at this moment, you should probably used an SV2 supporting pool such as Braiins Pool.

I think it's a great point that we link to Config C to that tutorial on the website. We're hoping to have config ready once this one  https://github.com/stratum-mining/stratum/pull/171 is done, and we fix bug(s) we found in our Pool https://github.com/stratum-mining/stratum/issues/356, may take a couple of weekd, but if you test the Config C with Translation proxy and Braiins, please let us know, would love to hear if you managed to make it work. Also if you use [Discord](https://discord.gg/fsEW23wFYs), you can hop on there, I'm sure we'll be able to help if you get stuck somewhere.

**Comment by pavlenex** [comment]
I'd say the first task here is:

- [ ] Link to TP tutorial for Config C

As we keep extending stack, we should ensure every config has a proper doc/tutorial. Great point!

**Comment by Sjors** [comment]
I'll take a look at that tutorial!

> Also if you use [Discord](https://discord.gg/fsEW23wFYs), you can hop on there

I'm more of an IRC / Matrix kinda guy :-) But I might.
