### ISSUE TITLE
Add `/docs` directory for documentation and VuePress

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#143]
We should separate more cleanly `docs` from the actual website. I think first step would be moving over docs to `/docs` directory. This will be much cleaner once we add `blog` as well, to separate content and make it more obvious for people what's being added where.

**Comment by JosephAni** [comment]
Hey Pavlenex,
Do you have an example of how you want this done or elaborate more on moving the docs like being on the sidebar?

**Comment by Abhijay007** [comment]
@pavlenex do you need any assistance with this one?

**Comment by pavlenex** [comment]
Hmm, I am not really sure about this one tbh, but I think it would be good idea to separate /docs from the website and eventually blog, if you know how to do that, feel free to.
