### ISSUE TITLE
Rename `Explore docs` to `Get Started` and point to `GettingStarted.md`

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#144]
Once gettingstarted.md #142 is done, formatted properly we should use it as a main call to action, pointing people towards actually running things and giving it a try, and learning about SV2 via docs could be a secondary call to action.

**Comment by hi-malik** [comment]
Hi @pavlenex can you please assign this to me and explain a bit about the issue!

**Comment by pavlenex** [comment]
Hey @hi-malik

![Screenshot 2023-02-20 at 11 55 48](https://user-images.githubusercontent.com/36959754/220086104-bbdd7e0e-9dc1-4e38-a79f-4df7c8fab350.png)

There's this button that needs to redirect to the gettingstarted.md once #142 is done.

This issue is low-priority and should be done only after #142 and #145 are done.

Theoretically you can do a PR, but we need #142 and #145 before we can merge it in.

**Comment by hi-malik** [comment]
Now, I got it what you want is: I have to rename this `Explore Documentation` to **`Get Started`** and when someone click on it, it will forward to **GettingStarted.md**!

> I'm right?

**Comment by pavlenex** [comment]
Correct, but will be merged only once we do #142 which adds that page, and also #145 #146  which makes that page readable, because right now it's messed up.

**Comment by hi-malik** [comment]
Alright, @pavlenex assign this to me & I will make the necessary changes and after that, I will push it and whenever the task got completed merge the pull request for #144
