### ISSUE TITLE
Improve code boxes highlighting 

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#145]
Currently code is not rendered properly. 

[Preview](https://deploy-preview-142--startling-capybara-2231ea.netlify.app/getting-started.html)

We have to add that so that code tutorials visibility is better. Good [example is what LDK does  ](https://lightningdevkit.org/running-a-sample-ldk-node/) or what [BTCPay Server does ](https://docs.btcpayserver.org/Development/GreenFieldExample-NodeJS/)

**Comment by joshr4** [comment]
Code highlighting can be enabled by adding a language after the markdown triple backticks - https://prismjs.com/#supported-languages

I only see code snippets in your recent PR - https://github.com/stratum-mining/stratumprotocol.org/pull/142

**Comment by Abhijay007** [comment]
@pavlenex any assistance required on this one? or is it gonna covered in one of your open PRs?

**Comment by pavlenex** [comment]
@Abhijay007 I just got help from @dennisreimann on this one ,he suggested this, which I'll now add in my PR #142 

```
code {
  font-size: .9em;
  background-color: #282c34;
  padding: .2em .4em;
  border-radius: .5em;
}
```
