### ISSUE TITLE
[Footer] Weird obstacle in footer

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#15]
I already reported this, managed to replicate it on two separate Mac devices. There's a weird responsiveness problem with the icons.

Let me know if I can provide any more info. Replicated both locally and via netlify, def not a cache issue.

![Screenshot 2022-08-20 at 16 37 15](https://user-images.githubusercontent.com/36959754/185751889-a89dcba5-91ce-413e-9292-74129afe5646.png)

**Comment by pavlenex** [comment]
I only see this on Safari, but not on Firefox, cleared cache, perhaps someone else needs to replicate this.

**Comment by kouloumos** [comment]
I replicated this on Safari, but not on Chrome, Opera and Brave.

It seems that the issue has to do with scaling-related css properties not applied correctly on Safari as the size you are observing is the actual size of those svgs (see `viewBox`). 

The size of those icons seems to default to 24px on all screen sizes. The following patch fixes the issue but, lacking familiarity with this framework, I can't say for sure that it doesn't break anything else, although I've checked.

<details><summary>click for patch</summary>
<p>

```diff
diff --git a/src/.vuepress/styles/index.styl b/src/.vuepress/styles/index.styl
index fbfd6d7..e7c978f 100755
--- a/src/.vuepress/styles/index.styl
+++ b/src/.vuepress/styles/index.styl
@@ -129,3 +129,8 @@ ul, ol {
     justify-content: center;
     align-items: center;
 }
+
+.svg-object {
+    width: 24px;
+    height: 24px;
+}
\ No newline at end of file
diff --git a/src/.vuepress/theme/components/NavLink.vue b/src/.vuepress/theme/components/NavLink.vue
index b09f1a0..290a590 100644
--- a/src/.vuepress/theme/components/NavLink.vue
+++ b/src/.vuepress/theme/components/NavLink.vue
@@ -17,7 +17,7 @@
     :rel="rel"
     @focusout="focusoutAction"
   >
-    <img class="mr-3" v-if="iconUrl" :src="iconUrl" />
+    <img class="mr-3 svg-object" v-if="iconUrl" :src="iconUrl" />
     <span class="leading-6">{{ item.text }}</span>
   </a>
 </template>

```

</p>
</details>

**Comment by SeraBocca** [comment]
closing issue since it is resolved
