### ISSUE TITLE
Remove entities that are no longer funding project  to "past supporters"

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#194]
Remove following entities from `funders` section and add new section on the site `past supporters` and move following logos there:

- Bitmex 
- Summer of bitcoin
- Foundry
- Galaxy

We should probably, if possible move out "past supporters" out of "all contributors" tab as well.

This related to this section 
<img width="828" alt="Screenshot 2024-02-14 at 16 41 23" src="https://github.com/stratum-mining/stratumprotocol.org/assets/36959754/ac95bac6-aef4-401e-b68d-b3529a90d636">

**Comment by 0xSaksham** [comment]
Hey, I am working on this issue. Just having some dependency issues with nodejs

**Comment by pavlenex** [comment]
Alright @0xSaksham, hopefully you'll manage to resolve those 🚀

**Comment by pavlenex** [comment]
Also let's add Hut8 as adopters https://hut8.io
![hut8](https://github.com/stratum-mining/stratumprotocol.org/assets/36959754/65c3d64a-5add-4d16-a8bf-3f64d50ffb1d)

**Comment by 0xSaksham** [comment]
@pavlenex I was able to add the new tab past supporters but I still need to figure out a way to separate them.

I'll submit a draft PR today.

If you can help with the above, please let me know.

**Comment by pavlenex** [comment]
Hey @0xSaksham did  you make any progress on this one?

**Comment by 0xSaksham** [comment]
Yes, I have made progress but can't seem to be able to remove the past supporters tab from main tab.

Can you help?

I'll create a PR
