### ISSUE TITLE
Add `What is Stratum v2` section

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#20]
Once #17 is removed, we need to add another section to explain SV2.

Text:
```Stratum V2 is the next generation protocol for pooled mining. It focuses on making data transfers more efficient, reducing physical infrastructure requirements for mining operations, and increasing security. Additionally, Stratum V2 introduces three new sub-protocols that allow miners to select their own transaction sets through a negotiation process with pools, improving decentralization. ```

### How it looks now

![Screenshot 2022-08-31 at 23 19 47](https://user-images.githubusercontent.com/36959754/187786971-b3bb63d2-65d8-46b6-b3c3-56e6b12afe65.png)

### How it should look

![Screenshot 2022-08-31 at 23 10 06](https://user-images.githubusercontent.com/36959754/187787086-8aeb1749-78ee-47e5-8154-3d45dad80135.png)

Link to figma https://www.figma.com/file/H42PrGnniKFtbfqHYBGevj/Stratum?node-id=147%3A549

This issue can be tackled together with #19

**Comment by secondl1ght** [comment]
@SeraBocca do you want to do this one also or should I do it?

**Comment by pavlenex** [comment]
@secondl1ght This one is completed or?

**Comment by secondl1ght** [comment]
Doing it now

**Comment by secondl1ght** [comment]
PR is in https://github.com/stratum-mining/stratumprotocol.org/pull/35
