### ISSUE TITLE
Replace `Manufacturers, Pools, Miners` section with `Stratum V2 features section

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#21]
As said in #17 we're removing these since we don't have content for it and replacing it with a section that will explain SV2 features/benefits.

### What we have now and needs to be removed
![Screenshot 2022-08-31 at 23 21 48](https://user-images.githubusercontent.com/36959754/187787544-a5024df6-bf3a-4197-ac2f-576ec562aa61.png)

### What we should have after 

![Screenshot 2022-08-31 at 23 23 58](https://user-images.githubusercontent.com/36959754/187787675-1e3cba38-9e52-4a0d-bbdd-de2ca65cb1b9.png)

### Link to figma

https://www.figma.com/file/H42PrGnniKFtbfqHYBGevj/Stratum?node-id=0%3A1

**Comment by secondl1ght** [comment]
@SeraBocca are you working on this? I just want to make sure our work doesn't overlap.

**Comment by secondl1ght** [comment]
PR is in #31
