### ISSUE TITLE
Past supporters tab should be inline with others

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#212]
Aesthetical fix, but would be great if these can all be inline
![Screenshot 2024-04-25 at 14 49 58](https://github.com/stratum-mining/stratumprotocol.org/assets/36959754/930d9b5f-0ef7-4812-8814-7d1378470557)

**Comment by Gudnessuche** [comment]
Inline is a good option, also giving it a margin-top of 20px wouldn't be bad either. In-line makes it look cleaner tho

**Comment by pavlenex** [comment]
Good idea, wanna tackle this one @Gudnessuche ?

**Comment by Gudnessuche** [comment]
Sure
VuePress is quite niche, don't you think so.
So more contributors find interest, what say you about switching to React-vite?

**Comment by pavlenex** [comment]
@Gudnessuche What would be the reason to switch? VuePress worked quite okay for us, I wouldn't do such disruptive changes unless there's a real good reason for that.

**Comment by pavlenex** [comment]
Fixed in https://github.com/stratum-mining/stratumprotocol.org/pull/220
