### ISSUE TITLE
Display Stratum V2 e-zine and GitGab19 Master thesis more prominently

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#218]
I am not quite sure yet where this could be added (perhaps as a part of #217) but we have two amazing resources  that go quite in-depth on SV2.

- Master thesis on SV2 by @GitGab19 https://webthesis.biblio.polito.it/27678/ 
- [Zine](https://primal.net/e/note1fcmsnt59pkgmh4ssuputpfx82jynykrz098jww4g68cl7ahe3qnqp3pyll) by @satsie https://technicaldifficulties.io/zines/sv2_zine.pdf

We should first figure out how to display these (as a separate call to aciton, (read SV2 e-zine or thesis) or perhaps just stick them prominently on the resource page/learning center/docs?

**Comment by satsie** [comment]
Converting the zine into an 8 page PDF that you can flip through and read online (as opposed to the printer friendly 2 page format) is on my todo list. When you need it, let me know and I can get it to you!

**Comment by pavlenex** [comment]
Done https://github.com/stratum-mining/stratumprotocol.org/pull/227
