### ISSUE TITLE
Add better footer

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#23]
Before tackling footer, please validate with Gene on Slack if it's been 

Footer should point to:
- Twiter https://twitter.com/StratumV2
- GitHub https://github.com/stratum-mining/stratum
- Discrod https://discord.gg/fsEW23wFYs

Link to figma https://www.figma.com/file/H42PrGnniKFtbfqHYBGevj/Stratum?node-id=0%3A1

**Comment by secondl1ght** [comment]
PR https://github.com/stratum-mining/stratumprotocol.org/pull/37
