### ISSUE TITLE
Add who supports SV2 

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#24]
Until we get a confirmation from a few entities what you see on figma in this seciton is just a mockup and shouldnt' be implemeted until @moneyball confirms which entities are okay to go in there, reach out to him on BitcoinDesign Slack/SV2 Discord for confirmation.

Once you get confirmation from @moneyball reach out to Gene to make sure that area is ironed out, if so implement it 🚀 

![Screenshot 2022-08-31 at 23 34 16](https://user-images.githubusercontent.com/36959754/187789240-79ce5743-cab8-4a18-813c-0cbf427ba2f6.png)

**Comment by moneyball** [comment]
I'm in touch with all 5 and feeling reasonably optimistic about approvals.

**Comment by moneyball** [comment]
Mining companies interested in supporting sv2:
Braiins - approved
Blockstream - approved
Galaxy - approved
Foundry - approved
Block - approved

Design-wise, the above list is expected to grow to dozens, hopefully many dozens, so ideally we know how the design will grow with that.

Companies funding sv2 project:
Spiral - approved
BitMEX - pending approved but expected (I'd say go ahead and include given the probability is high of approval)
Galaxy - approved
Foundry - approved

**Comment by moneyball** [comment]
Block assets found here: https://block.xyz/mediakit

**Comment by moneyball** [comment]
@pavlenex can you chase down SVG assets from each company? If you aren't already connected with them let me know and I can help.

**Comment by cogentgene** [comment]
@moneyball is Summer of bitcoin on the funder's list? I saw this mentioned.

I got all of the SVG logos already except block (png - or we can use the dancing gif)

**Comment by moneyball** [comment]
Funding:
Summer of Bitcoin - approved

**Comment by moneyball** [comment]
BitMEX - approved

**Comment by secondl1ght** [comment]
PR is in https://github.com/stratum-mining/stratumprotocol.org/pull/34
