### ISSUE TITLE
Add `Who funds SV2 development section`

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#25]
Current supporters supporting devs are known and can be added.

- [https://Spiral.xyz](https://www.figma.com/exit?url=https%3A%2F%2Fspiral.xyz)
- [https://www.galaxy.com](https://www.figma.com/exit?url=https%3A%2F%2Fwww.galaxy.com)
- [http://foundrydigital.com](https://www.figma.com/exit?url=http%3A%2F%2Ffoundrydigital.com)
- [http://summerofbitcoin.org](https://www.figma.com/exit?url=http%3A%2F%2Fsummerofbitcoin.org)

![Screenshot 2022-08-31 at 23 33 27](https://user-images.githubusercontent.com/36959754/187789775-5f58b4d4-5839-4d19-92ac-cc45416fcc1b.png)

https://www.figma.com/file/H42PrGnniKFtbfqHYBGevj/Stratum?node-id=0%3A1

**Comment by cogentgene** [comment]
Added logos.

**Comment by secondl1ght** [comment]
PR is in #30

**Comment by secondl1ght** [comment]
Completed with #33
