### ISSUE TITLE
Create 404 page

### ISSUE THREAD

**Issue by secondl1ght** [stratum-mining/stratumprotocol.org#27]
We might want to add a custom 404 page that matches the design?

**Comment by secondl1ght** [comment]
I think this is ready for dev now?

**Comment by pavlenex** [comment]
Yup!

**Comment by SeraBocca** [comment]
@pavlenex which design should I use (there are several ones on figma)

**Comment by pavlenex** [comment]
Let's ping Gene on Slack, to me they all look great but let's settle with one :)

**Comment by secondl1ght** [comment]
@SeraBocca did you start working on this?
