### ISSUE TITLE
Transfer SV2 Documentation from Braiins website to our doc (?)

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#28]
Braiins expressed interest to transfer over everything from https://braiins.com/stratum-v2 to our independent website. However we won't this for the MVP. This is in ideation phase and we will work on it after the website launch collaborating with their team on making the transition smooth for them and us.

**Comment by Kodylow** [comment]
I transferred and rewrote everything from the "Features" section in PR #14 , that's what's currently under the "implementation.md" section.
