### ISSUE TITLE
Docs section style updates

### ISSUE THREAD

**Issue by secondl1ght** [stratum-mining/stratumprotocol.org#55]
I just noticed a few small details we could fix on the documentation section (didn't have time to fix so I am posting here):

- ~~Left nav the padding on the top should match the botttom (the bottom has padding but the top doesn't)
Top~~
![image](https://user-images.githubusercontent.com/85003930/188750990-d720a285-9226-41e3-8f6d-03849e997abd.png)
Bottom
![image](https://user-images.githubusercontent.com/85003930/188751011-aae46aae-94f5-453b-9d70-b5f3825c3398.png)

- Nav menu on medium screens is broken - needs to be solid background 
![image](https://user-images.githubusercontent.com/85003930/188751191-edeaa936-e3f8-4dda-9039-d1f79e7f3947.png)

- Same padding issue here (below 'Specifications' and before the break line there should be the same padding that is on the top
![image](https://user-images.githubusercontent.com/85003930/188751456-39ab46e9-4f37-4fd0-aa3e-7710ee3af82c.png)

- Can the bottom of the left nav line up with the bottom of the docs when you scroll to the bottom? 
![image](https://user-images.githubusercontent.com/85003930/188751671-5da78b15-ff19-4a77-b4fd-23b0fa86c53c.png)

**Comment by pavlenex** [comment]
@secondl1ght do you mind taking a look at teh master now and see if it addressed your concerns or is this something more we'd like to iron out?

**Comment by secondl1ght** [comment]
> @secondl1ght do you mind taking a look at teh master now and see if it addressed your concerns or is this something more we'd like to iron out?

Looks like the top item has been fixed so I marked it out as done.

**Comment by secondl1ght** [comment]
Adding another bug here: when you click on 'Read the Docs' button at the bottom of the landing page, the page starts at the bottom and scrolls up which is kind of weird behavior.

**Comment by secondl1ght** [comment]
Documenting a few more bugs I noticed:

- Under Specification there are no links in the navbar:
![image](https://user-images.githubusercontent.com/85003930/189512085-645396a9-6a39-45ae-8be4-f8ca85d12897.png)

- Navbar links do not reflect hierarchy of document, example: Sub-Protocols is a higher level section header so should be spaced out more the same as Roles
![image](https://user-images.githubusercontent.com/85003930/189512106-239bd61d-168c-402f-a2aa-8871b21b18d2.png)
