### ISSUE TITLE
Resize logos and add colored logos

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#56]
I know logo resize back and forth can be frustrating, but we should ensure enough credits is given to the entities that support us without them being the central figure of the entire website. Currently, the logos are way bigger than the content around them and are more prominent than roadmap for example. It's even bigger than the subtitle of that section which doesn't really look sensible imo.

- [ ] Make all logos on the website their default colour, not white.
- [ ] Resize the logos 
    - [ ] Make the `Current Supporters of Stratum V2` smaller
    - [ ] Make `Who feels SV2 is the right direction` a bit smaller than the `Supporters of Stratum V2` 

### What we currently have

![Screenshot 2022-09-07 at 1 40 39 AM](https://user-images.githubusercontent.com/36959754/188759156-2c6604d5-2aef-4a91-8ba0-6c2c5315c15e.png)
![Screenshot 2022-09-07 at 1 40 48 AM](https://user-images.githubusercontent.com/36959754/188759207-4016d5c2-b199-4902-a462-71b14209a932.png)

**Comment by secondl1ght** [comment]
I can do this but I think it is blocked by design (we need the newly sized assets with the default colors), once we have those we can update on dev.
