### ISSUE TITLE
Add an actual email as cta

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#57]
Right now we use test@stratumprotocol.org but it should be an actual email

- [ ] Ping domain owner to configure a mailbox
- [ ] Replace it on the website

**Comment by secondl1ght** [comment]
Wouldn't it be better to accept donations directly on the website, through BTCPay Server or something like that?

**Comment by pavlenex** [comment]
That would require an entity to handle distribution, devs are just funded directly from external entities.

**Comment by secondl1ght** [comment]
Do we have an email for this yet?

**Comment by pavlenex** [comment]
@secondl1ght we don't I'll replace it once we do, this is a question of email governance, access, etc and it can take a while.
