### ISSUE TITLE
Remove two dots `..` from the intro paragraph

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#63]
![Screenshot 2022-09-07 at 18 02 44](https://user-images.githubusercontent.com/36959754/188926133-198bad87-c490-4fb4-97e6-44e76c327dc4.png)

**Comment by pavlenex** [comment]
I just couldn't quickly figure out why there are two dots when there's only one in text so something  from the code or a particle is probably causing this

**Comment by secondl1ght** [comment]
It looks like this happened because some code I had in this PR https://github.com/stratum-mining/stratumprotocol.org/pull/40/files got removed at some point, fixing now.
