### ISSUE TITLE
Cannot tell that the bottom rock is levitating. Perhaps increase vertical distance?

### ISSUE THREAD

**Issue by cogentgene** [stratum-mining/stratumprotocol.org#75]
May need movement distance increased. Can barely see the movement right now
![CleanShot 0004-09-08 at 22 29 28@2x](https://user-images.githubusercontent.com/3827304/189134882-d46a89a1-fbd3-4c6e-b51a-9e8cfe793956.jpg)

**Comment by secondl1ght** [comment]
You are right it is actually not moving at all.. XD. That demo I showed you was just me playing around locally and I never pushed it to prod, I decided to focus on the MVP and if we have time later we can add the animation effect.

**Comment by pavlenex** [comment]
Animations would be cool, lottie or? If this isn't something we'd like to tackle now (Though it would def be cool to add some plainfulness) should I remove the MVP label? @secondl1ght @cogentgene ?

**Comment by secondl1ght** [comment]
Yes for sure, I didn't think about lottie - I was just going to use old fashioned CSS. But if you wanted to play around with lottie @cogentgene that would work too.

**Comment by pavlenex** [comment]
So should we rename this issue to Implement Lottie, or is this something that we consider out of scope for now?
