### ISSUE TITLE
Pull specs from the specification repo and present them on the website

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#76]
Maintaining a separate specs text could pontentially mean that in the future we can go out of sync with the specs repository. 
I'd like to propose that we pull specs directly from specs repo so that any changes merged there is automatically deployed on our website.

@SeraBocca let me know if this makes sense, if you're not sure on the approach, I can dig a bit to see what we did with BTCPay.

https://github.com/stratum-mining/sv2-spec

**Comment by secondl1ght** [comment]
FYI @Kodylow is doing this
