### ISSUE TITLE
Add hover states to landing page links

### ISSUE THREAD

**Issue by secondl1ght** [stratum-mining/stratumprotocol.org#93]
Designs in the Figma file.

**Comment by developer-irfan** [comment]
@secondl1ght can you elaborate more? so i can solve the issue

**Comment by secondl1ght** [comment]
> @secondl1ght can you elaborate more? so i can solve the issue

Hi there, sorry we are on a bit of a tight time schedule so I went ahead and finished this issue myself. Next time I will make sure to provide more detail so somebody else can take on the issue right away. Thanks :)

**Comment by developer-irfan** [comment]
@secondl1ght ok.
