### ISSUE TITLE
Add tabbed view for multiple configurations

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#95]
In SV2, there's a variety of possible configurations, currently we're displaying only one "a complete configuration". It would be nice if we could showcase different configs and educate people on what they do and how they can be used.

@cogentgene provided an early concept of how that page may look like, but we still have to put it in Figma.

- [x] Design tabbed view in Figma
- [ ] Design mockups of configurations
- [ ] Make configurations match the design of the one we already have
- [x] Implement tabbed view and configurations
- [ ] Write the copy explaining configurations

### What we currently have

![Screenshot 2022-09-10 at 12 30 21](https://user-images.githubusercontent.com/36959754/189479549-fa1ab16a-c643-4fe6-9f65-25dc70907a93.png)

### Early idea of how this section may look like in a tabbed view
![cleanshot_0004-09-09_at_19 31 12_2x](https://user-images.githubusercontent.com/36959754/189479554-60cfb688-eaaa-4539-92bc-50c8444531d0.jpg)

**Comment by cogentgene** [comment]
Designed a frame but did not put it into the main design - was not sure how soon this is going live. I let the switcher on top because the graphics might be different heights and would jump around. Seeing it on top keeps the screen from jumping, and just easier to see your options. 

We can combine it with a label if necessary (perhaps left aligned of that button group area).

![CleanShot 0004-09-11 at 23 30 41@2x](https://user-images.githubusercontent.com/3827304/189533108-8c114d3d-5d3c-4d72-82df-63e0745cb41b.jpg)

**Comment by pavlenex** [comment]
@cogentgene I assume the description for each config can be before the graphic itself? The design looks really nice to me.

**Comment by pavlenex** [comment]
As for shipping it, I think it would be nice to have this one ready for an MVP.

**Comment by cogentgene** [comment]
> As for shipping it, I think it would be nice to have this one ready for an MVP.

Would that mean we need to have new graphics for each? That could be a lot of work.

**Comment by pavlenex** [comment]
I can take care of that it's mostly text changes.

**Comment by cogentgene** [comment]
@pavlenex ok, added to main design with text within the tab content.

Let me know if there's anything else we need here.

**Comment by pavlenex** [comment]
Alright, @secondl1ght @SeraBocca this is now ready for tackle, I'll label it accordingly.
![Screenshot 2022-09-12 at 10 17 46](https://user-images.githubusercontent.com/36959754/189605803-4be627f1-427b-4714-a5dc-0805bcf8a261.png)

**Comment by secondl1ght** [comment]
We still need the new graphics and text for this right?

**Comment by pavlenex** [comment]
@secondl1ght I think for now we can just add placeholders from config 1, once we're done I can take care of replacing them. Still need to make sure they're technically correct.
